//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.07 at 11:00:18 AM IST 
//

package com.tiny.sendXmlPojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
},namespace="")
@XmlRootElement(name = "FIXML")
public class FIXML {
	

	@XmlElement(name = "Header", required = true)
    protected FIXML.Header header;
    @XmlElement(name = "Body", required = true)
    protected FIXML.Body body;

    public FIXML.Header getHeader() {
        return header;
    }
    public void setHeader(FIXML.Header value) {
        this.header = value;
    }
    public FIXML.Body getBody() {
        return body;
    }
    public void setBody(FIXML.Body value) {
        this.body = value;
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ccAddDoc"
    })
    public static class Body {

        public Body() {
			super();
		}

		public Body(CCAddDoc ccAddDoc) {
			super();
			this.ccAddDoc = ccAddDoc;
		}


		@XmlElement(name = "CC_AddDoc", required = true)
        protected FIXML.Body.CCAddDoc ccAddDoc;

        /**
         * Gets the value of the ccAddDoc property.
         * 
         * @return
         *     possible object is
         *     {@link FIXML.Body.CCAddDoc }
         *     
         */
        public FIXML.Body.CCAddDoc getCCAddDoc() {
            return ccAddDoc;
        }

        /**
         * Sets the value of the ccAddDoc property.
         * 
         * @param value
         *     allowed object is
         *     {@link FIXML.Body.CCAddDoc }
         *     
         */
        public void setCCAddDoc(FIXML.Body.CCAddDoc value) {
            this.ccAddDoc = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DocumentProps">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="base64Encoded" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ParentFolderIndex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="documentPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="documentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="docNameExtn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="noOfPages" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="DocumentSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="userPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="document" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="FolderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="DataClassAttribs">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="dataDefIndex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="dataDefName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="IndexInfo" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="indexId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="indexValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "documentProps",
            "dataClassAttribs"
        })
        public static class CCAddDoc {

            public CCAddDoc() {
				super();
			}

			public CCAddDoc(DocumentProps documentProps, DataClassAttribs dataClassAttribs) {
				super();
				this.documentProps = documentProps;
				this.dataClassAttribs = dataClassAttribs;
			}


			@XmlElement(name = "DocumentProps", required = true)
            protected FIXML.Body.CCAddDoc.DocumentProps documentProps;
            @XmlElement(name = "DataClassAttribs", required = true)
            protected FIXML.Body.CCAddDoc.DataClassAttribs dataClassAttribs;

            /**
             * Gets the value of the documentProps property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Body.CCAddDoc.DocumentProps }
             *     
             */
            public FIXML.Body.CCAddDoc.DocumentProps getDocumentProps() {
                return documentProps;
            }

            /**
             * Sets the value of the documentProps property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Body.CCAddDoc.DocumentProps }
             *     
             */
            public void setDocumentProps(FIXML.Body.CCAddDoc.DocumentProps value) {
                this.documentProps = value;
            }

            /**
             * Gets the value of the dataClassAttribs property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Body.CCAddDoc.DataClassAttribs }
             *     
             */
            public FIXML.Body.CCAddDoc.DataClassAttribs getDataClassAttribs() {
                return dataClassAttribs;
            }

            /**
             * Sets the value of the dataClassAttribs property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Body.CCAddDoc.DataClassAttribs }
             *     
             */
            public void setDataClassAttribs(FIXML.Body.CCAddDoc.DataClassAttribs value) {
                this.dataClassAttribs = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="dataDefIndex" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="dataDefName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="IndexInfo" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="indexId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="indexValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dataDefIndex",
                "dataDefName",
                "indexInfo"
            })
            public static class DataClassAttribs {
            	
                public DataClassAttribs() {
					super();
				}

				public DataClassAttribs(String dataDefIndex, String dataDefName, List<IndexInfo> indexInfo) {
					super();
					this.dataDefIndex = dataDefIndex;
					this.dataDefName = dataDefName;
					this.indexInfo = indexInfo;
				}


				@XmlElement(required = true)
                protected String dataDefIndex;
                @XmlElement(required = true)
                protected String dataDefName;
                @XmlElement(name = "IndexInfo")
                protected List<FIXML.Body.CCAddDoc.DataClassAttribs.IndexInfo> indexInfo;

                /**
                 * Gets the value of the dataDefIndex property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDataDefIndex() {
                    return dataDefIndex;
                }

                /**
                 * Sets the value of the dataDefIndex property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDataDefIndex(String value) {
                    this.dataDefIndex = value;
                }

                /**
                 * Gets the value of the dataDefName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDataDefName() {
                    return dataDefName;
                }

                /**
                 * Sets the value of the dataDefName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDataDefName(String value) {
                    this.dataDefName = value;
                }

                /**
                 * Gets the value of the indexInfo property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the indexInfo property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getIndexInfo().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FIXML.Body.CCAddDoc.DataClassAttribs.IndexInfo }
                 * 
                 * 
                 */
                public List<FIXML.Body.CCAddDoc.DataClassAttribs.IndexInfo> getIndexInfo() {
                    if (indexInfo == null) {
                        indexInfo = new ArrayList<FIXML.Body.CCAddDoc.DataClassAttribs.IndexInfo>();
                    }
                    return this.indexInfo;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="indexId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="indexValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "indexId",
                    "indexValue"
                })
                public static class IndexInfo {

                    public IndexInfo() {
						super();
					}

					public IndexInfo(int indexId, String indexValue) {
						super();
						this.indexId = indexId;
						this.indexValue = indexValue;
					}

					protected int indexId;
                    @XmlElement(required = true)
                    protected String indexValue;

                    /**
                     * Gets the value of the indexId property.
                     * 
                     */
                    public int getIndexId() {
                        return indexId;
                    }

                    /**
                     * Sets the value of the indexId property.
                     * 
                     */
                    public void setIndexId(int value) {
                        this.indexId = value;
                    }

                    /**
                     * Gets the value of the indexValue property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIndexValue() {
                        return indexValue;
                    }

                    /**
                     * Sets the value of the indexValue property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIndexValue(String value) {
                        this.indexValue = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="base64Encoded" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ParentFolderIndex" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="documentPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="documentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="documentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="docNameExtn" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="noOfPages" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="DocumentSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="userPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="document" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="FolderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "base64Encoded",
                "parentFolderIndex",
                "documentPath",
                "documentName",
                "documentType",
                "docNameExtn",
                "noOfPages",
                "documentSize",
                "userName",
                "userPassword",
                "document",
                "folderName"
            })
            public static class DocumentProps {

                public DocumentProps() {
					super();
				}

				public DocumentProps(String base64Encoded, String parentFolderIndex, String documentPath,
						String documentName, String documentType, String docNameExtn, String noOfPages, int documentSize,
						String userName, String userPassword, String document, String folderName) {
					super();
					this.base64Encoded = base64Encoded;
					this.parentFolderIndex = parentFolderIndex;
					this.documentPath = documentPath;
					this.documentName = documentName;
					this.documentType = documentType;
					this.docNameExtn = docNameExtn;
					this.noOfPages = noOfPages;
					this.documentSize = documentSize;
					this.userName = userName;
					this.userPassword = userPassword;
					this.document = document;
					this.folderName = folderName;
				}

				@XmlElement(required = true)
                protected String base64Encoded;
                @XmlElement(name = "ParentFolderIndex", required = true)
                protected String parentFolderIndex;
                @XmlElement(required = true)
                protected String documentPath;
                @XmlElement(required = true)
                protected String documentName;
                @XmlElement(required = true)
                protected String documentType;
                @XmlElement(required = true)
                protected String docNameExtn;
                protected String noOfPages;
                @XmlElement(name = "DocumentSize")
                protected int documentSize;
                @XmlElement(required = true)
                protected String userName;
                @XmlElement(required = true)
                protected String userPassword;
                @XmlElement(required = true)
                protected String document;
                @XmlElement(name = "FolderName", required = true)
                protected String folderName;

                /**
                 * Gets the value of the base64Encoded property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBase64Encoded() {
                    return base64Encoded;
                }

                /**
                 * Sets the value of the base64Encoded property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBase64Encoded(String value) {
                    this.base64Encoded = value;
                }

                /**
                 * Gets the value of the parentFolderIndex property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParentFolderIndex() {
                    return parentFolderIndex;
                }

                /**
                 * Sets the value of the parentFolderIndex property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParentFolderIndex(String value) {
                    this.parentFolderIndex = value;
                }

                /**
                 * Gets the value of the documentPath property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDocumentPath() {
                    return documentPath;
                }

                /**
                 * Sets the value of the documentPath property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDocumentPath(String value) {
                    this.documentPath = value;
                }

                /**
                 * Gets the value of the documentName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDocumentName() {
                    return documentName;
                }

                /**
                 * Sets the value of the documentName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDocumentName(String value) {
                    this.documentName = value;
                }

                /**
                 * Gets the value of the documentType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDocumentType() {
                    return documentType;
                }

                /**
                 * Sets the value of the documentType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDocumentType(String value) {
                    this.documentType = value;
                }

                /**
                 * Gets the value of the docNameExtn property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDocNameExtn() {
                    return docNameExtn;
                }

                /**
                 * Sets the value of the docNameExtn property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDocNameExtn(String value) {
                    this.docNameExtn = value;
                }

                /**
                 * Gets the value of the noOfPages property.
                 * 
                 */
                public String getNoOfPages() {
                    return noOfPages;
                }

                /**
                 * Sets the value of the noOfPages property.
                 * 
                 */
                public void setNoOfPages(String value) {
                    this.noOfPages = value;
                }

                /**
                 * Gets the value of the documentSize property.
                 * 
                 */
                public int getDocumentSize() {
                    return documentSize;
                }

                /**
                 * Sets the value of the documentSize property.
                 * 
                 */
                public void setDocumentSize(int value) {
                    this.documentSize = value;
                }

                /**
                 * Gets the value of the userName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUserName() {
                    return userName;
                }

                /**
                 * Sets the value of the userName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUserName(String value) {
                    this.userName = value;
                }

                /**
                 * Gets the value of the userPassword property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUserPassword() {
                    return userPassword;
                }

                /**
                 * Sets the value of the userPassword property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUserPassword(String value) {
                    this.userPassword = value;
                }

                /**
                 * Gets the value of the document property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDocument() {
                    return document;
                }

                /**
                 * Sets the value of the document property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDocument(String value) {
                    this.document = value;
                }

                /**
                 * Gets the value of the folderName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFolderName() {
                    return folderName;
                }

                /**
                 * Sets the value of the folderName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFolderName(String value) {
                    this.folderName = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RequestHeader">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MessageKey">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RequestMessageInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Security">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Token">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="PasswordToken">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestHeader"
    })
    public static class Header {

        @XmlElement(name = "RequestHeader", required = true)
        protected FIXML.Header.RequestHeader requestHeader;

        /**
         * Gets the value of the requestHeader property.
         * 
         * @return
         *     possible object is
         *     {@link FIXML.Header.RequestHeader }
         *     
         */
        public FIXML.Header.RequestHeader getRequestHeader() {
            return requestHeader;
        }

        /**
         * Sets the value of the requestHeader property.
         * 
         * @param value
         *     allowed object is
         *     {@link FIXML.Header.RequestHeader }
         *     
         */
        public void setRequestHeader(FIXML.Header.RequestHeader value) {
            this.requestHeader = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MessageKey">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RequestMessageInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Security">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Token">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="PasswordToken">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "messageKey",
            "requestMessageInfo",
            "security"
        })
        public static class RequestHeader {

            @XmlElement(name = "MessageKey", required = true)
            protected FIXML.Header.RequestHeader.MessageKey messageKey;
            @XmlElement(name = "RequestMessageInfo", required = true)
            protected FIXML.Header.RequestHeader.RequestMessageInfo requestMessageInfo;
            @XmlElement(name = "Security", required = true)
            protected FIXML.Header.RequestHeader.Security security;
            public RequestHeader() {
	
            }
            @Override
			public String toString() {
				return "RequestHeader [messageKey=" + messageKey + ", requestMessageInfo=" + requestMessageInfo
						+ ", security=" + security + "]";
			}
			public RequestHeader(MessageKey messageKey, RequestMessageInfo requestMessageInfo, Security security) {
				super();
				this.messageKey = messageKey;
				this.requestMessageInfo = requestMessageInfo;
				this.security = security;
			}

			/**
             * Gets the value of the messageKey property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Header.RequestHeader.MessageKey }
             *     
             */
            public FIXML.Header.RequestHeader.MessageKey getMessageKey() {
                return messageKey;
            }

            /**
             * Sets the value of the messageKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Header.RequestHeader.MessageKey }
             *     
             */
            public void setMessageKey(FIXML.Header.RequestHeader.MessageKey value) {
                this.messageKey = value;
            }

            /**
             * Gets the value of the requestMessageInfo property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Header.RequestHeader.RequestMessageInfo }
             *     
             */
            public FIXML.Header.RequestHeader.RequestMessageInfo getRequestMessageInfo() {
                return requestMessageInfo;
            }

            /**
             * Sets the value of the requestMessageInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Header.RequestHeader.RequestMessageInfo }
             *     
             */
            public void setRequestMessageInfo(FIXML.Header.RequestHeader.RequestMessageInfo value) {
                this.requestMessageInfo = value;
            }

            /**
             * Gets the value of the security property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Header.RequestHeader.Security }
             *     
             */
            public FIXML.Header.RequestHeader.Security getSecurity() {
                return security;
            }

            /**
             * Sets the value of the security property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Header.RequestHeader.Security }
             *     
             */
            public void setSecurity(FIXML.Header.RequestHeader.Security value) {
                this.security = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "requestUUID",
                "serviceRequestId",
                "serviceRequestVersion",
                "channelId",
                "languageId"
            })
            public static class MessageKey {

                @XmlElement(name = "RequestUUID", required = true)
                protected String requestUUID;
                @XmlElement(name = "ServiceRequestId", required = true)
                protected String serviceRequestId;
                @XmlElement(name = "ServiceRequestVersion")
                protected float serviceRequestVersion;
                @XmlElement(name = "ChannelId", required = true)
                protected String channelId;
                @XmlElement(name = "LanguageId", required = true)
                protected String languageId;

              public  MessageKey(){
                	
                }
              public  MessageKey(String requestUUID,String serviceRequestId,float serviceRequestVersion,String channelId,String languageId){
            	  		this.requestUUID=requestUUID;
            	  		this.serviceRequestId=serviceRequestId;
            	  		this.serviceRequestVersion=serviceRequestVersion;
            	  		this.channelId=channelId;
            	  		this.languageId=languageId;
              }
                @Override
			public String toString() {
				return "MessageKey [requestUUID=" + requestUUID + ", serviceRequestId=" + serviceRequestId
						+ ", serviceRequestVersion=" + serviceRequestVersion + ", channelId=" + channelId
						+ ", languageId=" + languageId + "]";
			}
				/**
                 * Gets the value of the requestUUID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequestUUID() {
                    return requestUUID;
                }

                /**
                 * Sets the value of the requestUUID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequestUUID(String value) {
                    this.requestUUID = value;
                }

                /**
                 * Gets the value of the serviceRequestId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceRequestId() {
                    return serviceRequestId;
                }

                /**
                 * Sets the value of the serviceRequestId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceRequestId(String value) {
                    this.serviceRequestId = value;
                }

                /**
                 * Gets the value of the serviceRequestVersion property.
                 * 
                 */
                public float getServiceRequestVersion() {
                    return serviceRequestVersion;
                }

                /**
                 * Sets the value of the serviceRequestVersion property.
                 * 
                 */
                public void setServiceRequestVersion(float value) {
                    this.serviceRequestVersion = value;
                }

                /**
                 * Gets the value of the channelId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChannelId() {
                    return channelId;
                }

                /**
                 * Sets the value of the channelId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChannelId(String value) {
                    this.channelId = value;
                }

                /**
                 * Gets the value of the languageId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLanguageId() {
                    return languageId;
                }

                /**
                 * Sets the value of the languageId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLanguageId(String value) {
                    this.languageId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bankId",
                "timeZone",
                "entityId",
                "entityType",
                "armCorrelationId",
                "messageDateTime"
            })
            public static class RequestMessageInfo {

                

				@XmlElement(name = "BankId", required = true)
                protected String bankId;
                @XmlElement(name = "TimeZone", required = true)
                protected String timeZone;
                @XmlElement(name = "EntityId", required = true)
                protected String entityId;
                @XmlElement(name = "EntityType", required = true)
                protected String entityType;
                @XmlElement(name = "ArmCorrelationId", required = true)
                protected String armCorrelationId;
                @XmlElement(name = "MessageDateTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected String messageDateTime;
                public RequestMessageInfo() {
                	
                }
                public RequestMessageInfo(String bankId, String timeZone, String entityId, String entityType,
						String armCorrelationId, String messageDateTime) {
					super();
					this.bankId = bankId;
					this.timeZone = timeZone;
					this.entityId = entityId;
					this.entityType = entityType;
					this.armCorrelationId = armCorrelationId;
					this.messageDateTime = messageDateTime;
				}
                @Override
				public String toString() {
					return "RequestMessageInfo [bankId=" + bankId + ", timeZone=" + timeZone + ", entityId=" + entityId
							+ ", entityType=" + entityType + ", armCorrelationId=" + armCorrelationId
							+ ", messageDateTime=" + messageDateTime + "]";
				}
				/**
                 * Gets the value of the bankId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBankId() {
                    return bankId;
                }

                /**
                 * Sets the value of the bankId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBankId(String value) {
                    this.bankId = value;
                }

                /**
                 * Gets the value of the timeZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTimeZone() {
                    return timeZone;
                }

                /**
                 * Sets the value of the timeZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTimeZone(String value) {
                    this.timeZone = value;
                }

                /**
                 * Gets the value of the entityId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEntityId() {
                    return entityId;
                }

                /**
                 * Sets the value of the entityId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEntityId(String value) {
                    this.entityId = value;
                }

                /**
                 * Gets the value of the entityType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEntityType() {
                    return entityType;
                }

                /**
                 * Sets the value of the entityType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEntityType(String value) {
                    this.entityType = value;
                }

                /**
                 * Gets the value of the armCorrelationId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArmCorrelationId() {
                    return armCorrelationId;
                }

                /**
                 * Sets the value of the armCorrelationId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArmCorrelationId(String value) {
                    this.armCorrelationId = value;
                }

                /**
                 * Gets the value of the messageDateTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public String getMessageDateTime() {
                    return messageDateTime;
                }

                /**
                 * Sets the value of the messageDateTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setMessageDateTime(String value) {
                    this.messageDateTime = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Token">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="PasswordToken">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "token",
                "fiCertToken",
                "realUserLoginSessionId",
                "realUser",
                "realUserPwd",
                "ssoTransferToken"
            })
            public static class Security {

                public Security(Token token, String fiCertToken, String realUserLoginSessionId, String realUser,
						String realUserPwd, String ssoTransferToken) {
					this.token = token;
					this.fiCertToken = fiCertToken;
					this.realUserLoginSessionId = realUserLoginSessionId;
					this.realUser = realUser;
					this.realUserPwd = realUserPwd;
					this.ssoTransferToken = ssoTransferToken;
				}
                public Security() {
				}


				@Override
				public String toString() {
					return "Security [token=" + token + ", fiCertToken=" + fiCertToken + ", realUserLoginSessionId="
							+ realUserLoginSessionId + ", realUser=" + realUser + ", realUserPwd=" + realUserPwd
							+ ", ssoTransferToken=" + ssoTransferToken + "]";
				}


				@XmlElement(name = "Token", required = true)
                protected FIXML.Header.RequestHeader.Security.Token token;
                @XmlElement(name = "FICertToken", required = true)
                protected String fiCertToken;
                @XmlElement(name = "RealUserLoginSessionId", required = true)
                protected String realUserLoginSessionId;
                @XmlElement(name = "RealUser", required = true)
                protected String realUser;
                @XmlElement(name = "RealUserPwd", required = true)
                protected String realUserPwd;
                @XmlElement(name = "SSOTransferToken", required = true)
                protected String ssoTransferToken;

                /**
                 * Gets the value of the token property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FIXML.Header.RequestHeader.Security.Token }
                 *     
                 */
                public FIXML.Header.RequestHeader.Security.Token getToken() {
                    return token;
                }

                /**
                 * Sets the value of the token property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FIXML.Header.RequestHeader.Security.Token }
                 *     
                 */
                public void setToken(FIXML.Header.RequestHeader.Security.Token value) {
                    this.token = value;
                }

                /**
                 * Gets the value of the fiCertToken property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFICertToken() {
                    return fiCertToken;
                }

                /**
                 * Sets the value of the fiCertToken property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFICertToken(String value) {
                    this.fiCertToken = value;
                }

                /**
                 * Gets the value of the realUserLoginSessionId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRealUserLoginSessionId() {
                    return realUserLoginSessionId;
                }

                /**
                 * Sets the value of the realUserLoginSessionId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRealUserLoginSessionId(String value) {
                    this.realUserLoginSessionId = value;
                }

                /**
                 * Gets the value of the realUser property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRealUser() {
                    return realUser;
                }

                /**
                 * Sets the value of the realUser property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRealUser(String value) {
                    this.realUser = value;
                }

                /**
                 * Gets the value of the realUserPwd property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRealUserPwd() {
                    return realUserPwd;
                }

                /**
                 * Sets the value of the realUserPwd property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRealUserPwd(String value) {
                    this.realUserPwd = value;
                }

                /**
                 * Gets the value of the ssoTransferToken property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSSOTransferToken() {
                    return ssoTransferToken;
                }

                /**
                 * Sets the value of the ssoTransferToken property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSSOTransferToken(String value) {
                    this.ssoTransferToken = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="PasswordToken">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "passwordToken"
                })
                public static class Token {

                    public Token(PasswordToken passwordToken) {
						this.passwordToken = passwordToken;
					}


					public Token() {
						super();
					}


					@XmlElement(name = "PasswordToken", required = true)
                    protected PasswordToken passwordToken;

                    /**
                     * Gets the value of the passwordToken property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link FIXML.Header.RequestHeader.Security.Token.PasswordToken }
                     *     
                     */
                    public PasswordToken getPasswordToken() {
                        return passwordToken;
                    }

                    /**
                     * Sets the value of the passwordToken property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link FIXML.Header.RequestHeader.Security.Token.PasswordToken }
                     *     
                     */
                    public void setPasswordToken(PasswordToken value) {
                        this.passwordToken = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "userId",
                        "password"
                    })
                    public static class PasswordToken {

                        public PasswordToken() {
							super();
						}

						public PasswordToken(String userId, String password) {
							this.userId = userId;
							this.password = password;
						}

						@XmlElement(name = "UserId", required = true)
                        protected String userId;
                        @XmlElement(name = "Password", required = true)
                        protected String password;

                        /**
                         * Gets the value of the userId property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getUserId() {
                            return userId;
                        }

                        /**
                         * Sets the value of the userId property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setUserId(String value) {
                            this.userId = value;
                        }

                        /**
                         * Gets the value of the password property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPassword() {
                            return password;
                        }

                        /**
                         * Sets the value of the password property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPassword(String value) {
                            this.password = value;
                        }

                    }

                }

            }

        }

    }

}
