//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.07 at 11:00:00 AM IST 
//


package com.tiny.viewXmlPojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RequestHeader">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MessageKey">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RequestMessageInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Security">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Token">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="PasswordToken">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ViewDocumentsRequest">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="docIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="volumeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="downloadLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "FIXML")
public class FIXML {

	public FIXML() {
		super();
	}

	public FIXML(Header header, Body body) {
		this.header = header;
		this.body = body;
	}


	@XmlElement(name = "Header", required = true)
    protected FIXML.Header header;
    @XmlElement(name = "Body", required = true)
    protected FIXML.Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link FIXML.Header }
     *     
     */
    public FIXML.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link FIXML.Header }
     *     
     */
    public void setHeader(FIXML.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link FIXML.Body }
     *     
     */
    public FIXML.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link FIXML.Body }
     *     
     */
    public void setBody(FIXML.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ViewDocumentsRequest">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="docIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="volumeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="downloadLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "viewDocumentsRequest"
    })
    public static class Body {

        public Body() {
			super();
		}

		public Body(ViewDocumentsRequest viewDocumentsRequest) {
			this.viewDocumentsRequest = viewDocumentsRequest;
		}


		@XmlElement(name = "ViewDocumentsRequest", required = true)
        protected FIXML.Body.ViewDocumentsRequest viewDocumentsRequest;

        /**
         * Gets the value of the viewDocumentsRequest property.
         * 
         * @return
         *     possible object is
         *     {@link FIXML.Body.ViewDocumentsRequest }
         *     
         */
        public FIXML.Body.ViewDocumentsRequest getViewDocumentsRequest() {
            return viewDocumentsRequest;
        }

        /**
         * Sets the value of the viewDocumentsRequest property.
         * 
         * @param value
         *     allowed object is
         *     {@link FIXML.Body.ViewDocumentsRequest }
         *     
         */
        public void setViewDocumentsRequest(FIXML.Body.ViewDocumentsRequest value) {
            this.viewDocumentsRequest = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="docIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="volumeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="downloadLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "docIndex",
            "fileName",
            "volumeId",
            "downloadLocation"
        })
        public static class ViewDocumentsRequest {

            public ViewDocumentsRequest() {
				super();
			}

			public ViewDocumentsRequest(String documentIndex, String fileName, String volumeId, String downloadLocation) {
				this.docIndex = documentIndex;
				this.fileName = fileName;
				this.volumeId = volumeId;
				this.downloadLocation = downloadLocation;
			}

			protected String docIndex;
            @XmlElement(required = true)
            protected String fileName;
            @XmlElement(required = true)
            protected String volumeId;
            @XmlElement(required = true)
            protected String downloadLocation;

            /**
             * Gets the value of the docIndex property.
             * 
             */
            public String getDocIndex() {
                return docIndex;
            }

            /**
             * Sets the value of the docIndex property.
             * 
             */
            public void setDocIndex(String value) {
                this.docIndex = value;
            }

            /**
             * Gets the value of the fileName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

            /**
             * Gets the value of the volumeId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVolumeId() {
                return volumeId;
            }

            /**
             * Sets the value of the volumeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVolumeId(String value) {
                this.volumeId = value;
            }

            /**
             * Gets the value of the downloadLocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDownloadLocation() {
                return downloadLocation;
            }

            /**
             * Sets the value of the downloadLocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDownloadLocation(String value) {
                this.downloadLocation = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RequestHeader">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MessageKey">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="RequestMessageInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Security">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Token">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="PasswordToken">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestHeader"
    })
    public static class Header {

        public Header() {
			super();
		}

		public Header(RequestHeader requestHeader) {
			this.requestHeader = requestHeader;
		}


		@XmlElement(name = "RequestHeader", required = true)
        protected FIXML.Header.RequestHeader requestHeader;

        /**
         * Gets the value of the requestHeader property.
         * 
         * @return
         *     possible object is
         *     {@link FIXML.Header.RequestHeader }
         *     
         */
        public FIXML.Header.RequestHeader getRequestHeader() {
            return requestHeader;
        }

        /**
         * Sets the value of the requestHeader property.
         * 
         * @param value
         *     allowed object is
         *     {@link FIXML.Header.RequestHeader }
         *     
         */
        public void setRequestHeader(FIXML.Header.RequestHeader value) {
            this.requestHeader = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MessageKey">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="RequestMessageInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Security">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Token">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="PasswordToken">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "messageKey",
            "requestMessageInfo",
            "security"
        })
        public static class RequestHeader {

            public RequestHeader() {
				super();
			}

			public RequestHeader(MessageKey messageKey, RequestMessageInfo requestMessageInfo, Security security) {
				this.messageKey = messageKey;
				this.requestMessageInfo = requestMessageInfo;
				this.security = security;
			}


			@XmlElement(name = "MessageKey", required = true)
            protected FIXML.Header.RequestHeader.MessageKey messageKey;
            @XmlElement(name = "RequestMessageInfo", required = true)
            protected FIXML.Header.RequestHeader.RequestMessageInfo requestMessageInfo;
            @XmlElement(name = "Security", required = true)
            protected FIXML.Header.RequestHeader.Security security;

            /**
             * Gets the value of the messageKey property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Header.RequestHeader.MessageKey }
             *     
             */
            public FIXML.Header.RequestHeader.MessageKey getMessageKey() {
                return messageKey;
            }

            /**
             * Sets the value of the messageKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Header.RequestHeader.MessageKey }
             *     
             */
            public void setMessageKey(FIXML.Header.RequestHeader.MessageKey value) {
                this.messageKey = value;
            }

            /**
             * Gets the value of the requestMessageInfo property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Header.RequestHeader.RequestMessageInfo }
             *     
             */
            public FIXML.Header.RequestHeader.RequestMessageInfo getRequestMessageInfo() {
                return requestMessageInfo;
            }

            /**
             * Sets the value of the requestMessageInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Header.RequestHeader.RequestMessageInfo }
             *     
             */
            public void setRequestMessageInfo(FIXML.Header.RequestHeader.RequestMessageInfo value) {
                this.requestMessageInfo = value;
            }

            /**
             * Gets the value of the security property.
             * 
             * @return
             *     possible object is
             *     {@link FIXML.Header.RequestHeader.Security }
             *     
             */
            public FIXML.Header.RequestHeader.Security getSecurity() {
                return security;
            }

            /**
             * Sets the value of the security property.
             * 
             * @param value
             *     allowed object is
             *     {@link FIXML.Header.RequestHeader.Security }
             *     
             */
            public void setSecurity(FIXML.Header.RequestHeader.Security value) {
                this.security = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "requestUUID",
                "serviceRequestId",
                "serviceRequestVersion",
                "channelId",
                "languageId"
            })
            public static class MessageKey {

                public MessageKey() {
					super();
				}

				public MessageKey(String requestUUID, String serviceRequestId, float serviceRequestVersion,
						String channelId, String languageId) {
					this.requestUUID = requestUUID;
					this.serviceRequestId = serviceRequestId;
					this.serviceRequestVersion = serviceRequestVersion;
					this.channelId = channelId;
					this.languageId = languageId;
				}

				@XmlElement(name = "RequestUUID", required = true)
                protected String requestUUID;
                @XmlElement(name = "ServiceRequestId", required = true)
                protected String serviceRequestId;
                @XmlElement(name = "ServiceRequestVersion")
                protected float serviceRequestVersion;
                @XmlElement(name = "ChannelId", required = true)
                protected String channelId;
                @XmlElement(name = "LanguageId", required = true)
                protected String languageId;

                /**
                 * Gets the value of the requestUUID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequestUUID() {
                    return requestUUID;
                }

                /**
                 * Sets the value of the requestUUID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequestUUID(String value) {
                    this.requestUUID = value;
                }

                /**
                 * Gets the value of the serviceRequestId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceRequestId() {
                    return serviceRequestId;
                }

                /**
                 * Sets the value of the serviceRequestId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceRequestId(String value) {
                    this.serviceRequestId = value;
                }

                /**
                 * Gets the value of the serviceRequestVersion property.
                 * 
                 */
                public float getServiceRequestVersion() {
                    return serviceRequestVersion;
                }

                /**
                 * Sets the value of the serviceRequestVersion property.
                 * 
                 */
                public void setServiceRequestVersion(float value) {
                    this.serviceRequestVersion = value;
                }

                /**
                 * Gets the value of the channelId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChannelId() {
                    return channelId;
                }

                /**
                 * Sets the value of the channelId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChannelId(String value) {
                    this.channelId = value;
                }

                /**
                 * Gets the value of the languageId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLanguageId() {
                    return languageId;
                }

                /**
                 * Sets the value of the languageId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLanguageId(String value) {
                    this.languageId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bankId",
                "timeZone",
                "entityId",
                "entityType",
                "armCorrelationId",
                "messageDateTime"
            })
            public static class RequestMessageInfo {

                public RequestMessageInfo() {
					super();
				}

				public RequestMessageInfo(byte bankId, String timeZone, String entityId, String entityType,
						String armCorrelationId, String messageDateTime) {
					this.bankId = bankId;
					this.timeZone = timeZone;
					this.entityId = entityId;
					this.entityType = entityType;
					this.armCorrelationId = armCorrelationId;
					this.messageDateTime = messageDateTime;
				}

				@XmlElement(name = "BankId")
                protected byte bankId;
                @XmlElement(name = "TimeZone", required = true)
                protected String timeZone;
                @XmlElement(name = "EntityId", required = true)
                protected String entityId;
                @XmlElement(name = "EntityType", required = true)
                protected String entityType;
                @XmlElement(name = "ArmCorrelationId", required = true)
                protected String armCorrelationId;
                @XmlElement(name = "MessageDateTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected String messageDateTime;

                /**
                 * Gets the value of the bankId property.
                 * 
                 */
                public byte getBankId() {
                    return bankId;
                }

                /**
                 * Sets the value of the bankId property.
                 * 
                 */
                public void setBankId(byte value) {
                    this.bankId = value;
                }

                /**
                 * Gets the value of the timeZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTimeZone() {
                    return timeZone;
                }

                /**
                 * Sets the value of the timeZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTimeZone(String value) {
                    this.timeZone = value;
                }

                /**
                 * Gets the value of the entityId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEntityId() {
                    return entityId;
                }

                /**
                 * Sets the value of the entityId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEntityId(String value) {
                    this.entityId = value;
                }

                /**
                 * Gets the value of the entityType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEntityType() {
                    return entityType;
                }

                /**
                 * Sets the value of the entityType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEntityType(String value) {
                    this.entityType = value;
                }

                /**
                 * Gets the value of the armCorrelationId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArmCorrelationId() {
                    return armCorrelationId;
                }

                /**
                 * Sets the value of the armCorrelationId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArmCorrelationId(String value) {
                    this.armCorrelationId = value;
                }

                /**
                 * Gets the value of the messageDateTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public String getMessageDateTime() {
                    return messageDateTime;
                }

                /**
                 * Sets the value of the messageDateTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setMessageDateTime(String value) {
                    this.messageDateTime = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Token">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="PasswordToken">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "token",
                "fiCertToken",
                "realUserLoginSessionId",
                "realUser",
                "realUserPwd",
                "ssoTransferToken"
            })
            public static class Security {

             

				public Security(com.tiny.sendXmlPojo.FIXML.Header.RequestHeader.Security.Token token, String fiCertToken,
						String realUserLoginSessionId, String realUser, String realUserPwd, String ssoTransferToken) {
					
					this.token = token;
					this.fiCertToken = fiCertToken;
					this.realUserLoginSessionId = realUserLoginSessionId;
					this.realUser = realUser;
					this.realUserPwd = realUserPwd;
					this.ssoTransferToken = ssoTransferToken;
				}

				public Security() {
					super();
				}


				@XmlElement(name = "Token", required = true)
                protected com.tiny.sendXmlPojo.FIXML.Header.RequestHeader.Security.Token token;
                @XmlElement(name = "FICertToken", required = true)
                protected String fiCertToken;
                @XmlElement(name = "RealUserLoginSessionId", required = true)
                protected String realUserLoginSessionId;
                @XmlElement(name = "RealUser", required = true)
                protected String realUser;
                @XmlElement(name = "RealUserPwd", required = true)
                protected String realUserPwd;
                @XmlElement(name = "SSOTransferToken", required = true)
                protected String ssoTransferToken;

                /**
                 * Gets the value of the token property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FIXML.Header.RequestHeader.Security.Token }
                 *     
                 */
                public com.tiny.sendXmlPojo.FIXML.Header.RequestHeader.Security.Token getToken() {
                    return token;
                }

                /**
                 * Sets the value of the token property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FIXML.Header.RequestHeader.Security.Token }
                 *     
                 */
                public void setToken(com.tiny.sendXmlPojo.FIXML.Header.RequestHeader.Security.Token value) {
                    this.token = value;
                }

                /**
                 * Gets the value of the fiCertToken property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFICertToken() {
                    return fiCertToken;
                }

                /**
                 * Sets the value of the fiCertToken property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFICertToken(String value) {
                    this.fiCertToken = value;
                }

                /**
                 * Gets the value of the realUserLoginSessionId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRealUserLoginSessionId() {
                    return realUserLoginSessionId;
                }

                /**
                 * Sets the value of the realUserLoginSessionId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRealUserLoginSessionId(String value) {
                    this.realUserLoginSessionId = value;
                }

                /**
                 * Gets the value of the realUser property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRealUser() {
                    return realUser;
                }

                /**
                 * Sets the value of the realUser property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRealUser(String value) {
                    this.realUser = value;
                }

                /**
                 * Gets the value of the realUserPwd property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRealUserPwd() {
                    return realUserPwd;
                }

                /**
                 * Sets the value of the realUserPwd property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRealUserPwd(String value) {
                    this.realUserPwd = value;
                }

                /**
                 * Gets the value of the ssoTransferToken property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSSOTransferToken() {
                    return ssoTransferToken;
                }

                /**
                 * Sets the value of the ssoTransferToken property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSSOTransferToken(String value) {
                    this.ssoTransferToken = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="PasswordToken">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "passwordToken"
                })
                public static class Token {

                    public Token() {
						super();
					}

					public Token(String passwordToken) {
						this.passwordToken = passwordToken;
					}


					@XmlElement(name = "PasswordToken", required = true)
                    protected String passwordToken;

                    /**
                     * Gets the value of the passwordToken property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link FIXML.Header.RequestHeader.Security.Token.PasswordToken }
                     *     
                     */
                    public String getPasswordToken() {
                        return passwordToken;
                    }

                    /**
                     * Sets the value of the passwordToken property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link FIXML.Header.RequestHeader.Security.Token.PasswordToken }
                     *     
                     */
                    public void setPasswordToken(String value) {
                        this.passwordToken = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "userId",
                        "password"
                    })
                    public static class PasswordToken {

                        public PasswordToken() {
							super();
						}

						public PasswordToken(String userId, String password) {
							this.userId = userId;
							this.password = password;
						}

						@XmlElement(name = "UserId", required = true)
                        protected String userId;
                        @XmlElement(name = "Password", required = true)
                        protected String password;

                        /**
                         * Gets the value of the userId property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getUserId() {
                            return userId;
                        }

                        /**
                         * Sets the value of the userId property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setUserId(String value) {
                            this.userId = value;
                        }

                        /**
                         * Gets the value of the password property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPassword() {
                            return password;
                        }

                        /**
                         * Sets the value of the password property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPassword(String value) {
                            this.password = value;
                        }

                    }

                }

            }

        }

    }

}
